import { createFileRoute, Link } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Check, ExternalLink, MessageSquareWarning, X } from "lucide-react";
import { toast } from "sonner";
import { listPendingSubmissions, reviewSubmission } from "@/lib/data/submissions.functions";
import { useAuth } from "@/lib/auth";
import { toArray, toRecord } from "@/lib/turso/rows";
import { SiteHeader } from "@/components/SiteHeader";
import { SiteFooter } from "@/components/SiteFooter";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";

export const Route = createFileRoute("/_authenticated/curadoria/contribuicoes")({ component: Page });
function Page(){const {isReviewer,loading}=useAuth();const fetcher=useServerFn(listPendingSubmissions);const review=useServerFn(reviewSubmission);const qc=useQueryClient();const q=useQuery({queryKey:["submissions"],queryFn:()=>fetcher() as Promise<Record<string,unknown>[]>,enabled:isReviewer});const mutation=useMutation({mutationFn:({id,decision}:{id:string;decision:"approve"|"reject"|"needs_changes"})=>review({data:{id,decision,notes:""}}),onSuccess:()=>{toast.success("Decisão registrada.");qc.invalidateQueries({queryKey:["submissions"]})},onError:(e:Error)=>toast.error(e.message)});
return <Shell>{loading?<Skeleton className="h-40"/>:!isReviewer?<Restricted/>:<><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-eyebrow text-muted-foreground">Curadoria participativa</p><h1 className="font-display text-3xl font-semibold">Contribuições recebidas</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Nada é publicado automaticamente. Verifique autoria, contexto, licenças, fontes e a pertinência dos metadados sensíveis.</p></div><Badge variant="secondary">{q.data?.length??0} pendentes</Badge></div>{q.isLoading?<Skeleton className="h-72"/>:q.data?.length?q.data.map((r)=><Card key={String(r.id)} r={r} busy={mutation.isPending} decide={(decision)=>mutation.mutate({id:String(r.id),decision})}/>):<div className="rounded-xl border bg-card p-10 text-center text-muted-foreground">Nenhuma contribuição aguardando análise.</div>}</>}</Shell>}
function Card({r,busy,decide}:{r:Record<string,unknown>;busy:boolean;decide:(d:"approve"|"reject"|"needs_changes")=>void}){const sensitive=toRecord(r.sensitive_metadata);const poetic=toRecord(r.poetic_metadata);return <article className="mb-6 overflow-hidden rounded-2xl border bg-card"><div className="grid md:grid-cols-[240px_1fr]">{r.image_url?<img src={String(r.image_url)} alt="" className="h-full min-h-56 w-full object-cover"/>:<div className="min-h-48 bg-muted"/>}<div className="p-6"><div className="flex flex-wrap gap-2"><Badge>{String(r.submission_type)}</Badge><Badge variant="outline">{String(r.status)}</Badge></div><h2 className="mt-3 font-display text-2xl font-semibold">{String(r.title)}</h2>{r.artist_name&&<p className="text-sm text-muted-foreground">{String(r.artist_name)}</p>}<p className="mt-4 whitespace-pre-wrap text-sm leading-6">{String(r.description)}</p><Meta title="Contexto" values={[r.date_display,r.location,r.country,r.culture].filter(Boolean).map(String)}/><Meta title="Marcadores situados" values={Object.values(sensitive).flatMap((v)=>Array.isArray(v)?v:[String(v)])}/><Meta title="Metadados poéticos" values={Object.values(poetic).flatMap((v)=>Array.isArray(v)?v:[String(v)])}/><Meta title="Tags" values={toArray(r.tags)}/><div className="mt-4 text-xs text-muted-foreground">Enviado por {String(r.submitter_name)} · {String(r.submitter_email)}</div>{r.image_source_url&&<a className="mt-3 inline-flex items-center gap-1 text-xs underline" href={String(r.image_source_url)} target="_blank" rel="noreferrer"><ExternalLink className="h-3 w-3"/>ver fonte da imagem</a>}<div className="mt-6 flex flex-wrap gap-2"><Button disabled={busy} onClick={()=>decide("approve")}><Check className="mr-2 h-4 w-4"/>Aprovar e publicar</Button><Button disabled={busy} variant="outline" onClick={()=>decide("needs_changes")}><MessageSquareWarning className="mr-2 h-4 w-4"/>Pedir ajustes</Button><Button disabled={busy} variant="destructive" onClick={()=>decide("reject")}><X className="mr-2 h-4 w-4"/>Recusar</Button></div></div></div></article>}
function Meta({title,values}:{title:string;values:string[]}){if(!values.length)return null;return <div className="mt-4"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{title}</p><div className="mt-2 flex flex-wrap gap-2">{values.filter(Boolean).map((v,i)=><Badge key={`${v}-${i}`} variant="secondary">{v}</Badge>)}</div></div>}
function Restricted(){return <div className="rounded-xl border bg-card p-10 text-center"><h1 className="font-display text-2xl font-semibold">Acesso restrito</h1><p className="mt-2 text-muted-foreground">Somente administradores e curadores podem revisar contribuições.</p><Button asChild className="mt-5"><Link to="/">Voltar</Link></Button></div>}
function Shell({children}:{children:React.ReactNode}){return <div className="flex min-h-screen flex-col"><SiteHeader/><main className="mx-auto w-full max-w-6xl flex-1 px-4 py-10 sm:px-6">{children}</main><SiteFooter/></div>}
