/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedeRouteImport } from './routes/rede'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as MaesRouteImport } from './routes/maes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcervoIndexRouteImport } from './routes/acervo.index'
import { Route as AcervoIdRouteImport } from './routes/acervo.$id'
import { Route as AuthenticatedAtlasIndexRouteImport } from './routes/_authenticated/atlas.index'
import { Route as ApiAiHealthRouteImport } from './routes/api/ai/health'
import { Route as AuthenticatedCuradoriaImagensRouteImport } from './routes/_authenticated/curadoria.imagens'
import { Route as AuthenticatedAtlasAtlasIdRouteImport } from './routes/_authenticated/atlas.$atlasId'

const RedeRoute = RedeRouteImport.update({
  id: '/rede',
  path: '/rede',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const MaesRoute = MaesRouteImport.update({
  id: '/maes',
  path: '/maes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcervoIndexRoute = AcervoIndexRouteImport.update({
  id: '/acervo/',
  path: '/acervo/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcervoIdRoute = AcervoIdRouteImport.update({
  id: '/acervo/$id',
  path: '/acervo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAtlasIndexRoute = AuthenticatedAtlasIndexRouteImport.update({
  id: '/atlas/',
  path: '/atlas/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiAiHealthRoute = ApiAiHealthRouteImport.update({
  id: '/api/ai/health',
  path: '/api/ai/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCuradoriaImagensRoute =
  AuthenticatedCuradoriaImagensRouteImport.update({
    id: '/curadoria/imagens',
    path: '/curadoria/imagens',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAtlasAtlasIdRoute =
  AuthenticatedAtlasAtlasIdRouteImport.update({
    id: '/atlas/$atlasId',
    path: '/atlas/$atlasId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/maes': typeof MaesRoute
  '/mapa': typeof MapaRoute
  '/rede': typeof RedeRoute
  '/acervo/$id': typeof AcervoIdRoute
  '/acervo/': typeof AcervoIndexRoute
  '/atlas/$atlasId': typeof AuthenticatedAtlasAtlasIdRoute
  '/curadoria/imagens': typeof AuthenticatedCuradoriaImagensRoute
  '/api/ai/health': typeof ApiAiHealthRoute
  '/atlas/': typeof AuthenticatedAtlasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/maes': typeof MaesRoute
  '/mapa': typeof MapaRoute
  '/rede': typeof RedeRoute
  '/acervo/$id': typeof AcervoIdRoute
  '/acervo': typeof AcervoIndexRoute
  '/atlas/$atlasId': typeof AuthenticatedAtlasAtlasIdRoute
  '/curadoria/imagens': typeof AuthenticatedCuradoriaImagensRoute
  '/api/ai/health': typeof ApiAiHealthRoute
  '/atlas': typeof AuthenticatedAtlasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/maes': typeof MaesRoute
  '/mapa': typeof MapaRoute
  '/rede': typeof RedeRoute
  '/acervo/$id': typeof AcervoIdRoute
  '/acervo/': typeof AcervoIndexRoute
  '/_authenticated/atlas/$atlasId': typeof AuthenticatedAtlasAtlasIdRoute
  '/_authenticated/curadoria/imagens': typeof AuthenticatedCuradoriaImagensRoute
  '/api/ai/health': typeof ApiAiHealthRoute
  '/_authenticated/atlas/': typeof AuthenticatedAtlasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/maes'
    | '/mapa'
    | '/rede'
    | '/acervo/$id'
    | '/acervo/'
    | '/atlas/$atlasId'
    | '/curadoria/imagens'
    | '/api/ai/health'
    | '/atlas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/maes'
    | '/mapa'
    | '/rede'
    | '/acervo/$id'
    | '/acervo'
    | '/atlas/$atlasId'
    | '/curadoria/imagens'
    | '/api/ai/health'
    | '/atlas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/maes'
    | '/mapa'
    | '/rede'
    | '/acervo/$id'
    | '/acervo/'
    | '/_authenticated/atlas/$atlasId'
    | '/_authenticated/curadoria/imagens'
    | '/api/ai/health'
    | '/_authenticated/atlas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MaesRoute: typeof MaesRoute
  MapaRoute: typeof MapaRoute
  RedeRoute: typeof RedeRoute
  AcervoIdRoute: typeof AcervoIdRoute
  AcervoIndexRoute: typeof AcervoIndexRoute
  ApiAiHealthRoute: typeof ApiAiHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rede': {
      id: '/rede'
      path: '/rede'
      fullPath: '/rede'
      preLoaderRoute: typeof RedeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maes': {
      id: '/maes'
      path: '/maes'
      fullPath: '/maes'
      preLoaderRoute: typeof MaesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acervo/': {
      id: '/acervo/'
      path: '/acervo'
      fullPath: '/acervo/'
      preLoaderRoute: typeof AcervoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acervo/$id': {
      id: '/acervo/$id'
      path: '/acervo/$id'
      fullPath: '/acervo/$id'
      preLoaderRoute: typeof AcervoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/atlas/': {
      id: '/_authenticated/atlas/'
      path: '/atlas'
      fullPath: '/atlas/'
      preLoaderRoute: typeof AuthenticatedAtlasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/ai/health': {
      id: '/api/ai/health'
      path: '/api/ai/health'
      fullPath: '/api/ai/health'
      preLoaderRoute: typeof ApiAiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/curadoria/imagens': {
      id: '/_authenticated/curadoria/imagens'
      path: '/curadoria/imagens'
      fullPath: '/curadoria/imagens'
      preLoaderRoute: typeof AuthenticatedCuradoriaImagensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atlas/$atlasId': {
      id: '/_authenticated/atlas/$atlasId'
      path: '/atlas/$atlasId'
      fullPath: '/atlas/$atlasId'
      preLoaderRoute: typeof AuthenticatedAtlasAtlasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAtlasAtlasIdRoute: typeof AuthenticatedAtlasAtlasIdRoute
  AuthenticatedCuradoriaImagensRoute: typeof AuthenticatedCuradoriaImagensRoute
  AuthenticatedAtlasIndexRoute: typeof AuthenticatedAtlasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAtlasAtlasIdRoute: AuthenticatedAtlasAtlasIdRoute,
  AuthenticatedCuradoriaImagensRoute: AuthenticatedCuradoriaImagensRoute,
  AuthenticatedAtlasIndexRoute: AuthenticatedAtlasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MaesRoute: MaesRoute,
  MapaRoute: MapaRoute,
  RedeRoute: RedeRoute,
  AcervoIdRoute: AcervoIdRoute,
  AcervoIndexRoute: AcervoIndexRoute,
  ApiAiHealthRoute: ApiAiHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
